<?php

namespace App\Http\Requests;

use Illuminate\Validation\Rule;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rules;
use Illuminate\Support\Str;

class UpdateCarrierAccountRequest extends FormRequest
{


    private $cities =  [
        "Ada",
        "Aleksinac",
        "Apatin",
        "Arilje",
        "Avala",
        "Backa Topola",
        "Backi Jarak",
        "Backi Petrovac",
        "Backo Gradiste",
        "Banatsko Novo Selo",
        "Barajevo",
        "Basaid",
        "Batajnica",
        "Becej",
        "Belgrade",
        "Bocar",
        "Bor",
        "Cantavir",
        "Coka",
        "Cukarica",
        "Cuprija",
        "Debeljaca",
        "Despotovac",
        "Dolovo",
        "Drenovac",
        "Futog",
        "Glozan",
        "Golubinci",
        "Gornji Milanovac",
        "Grocka",
        "Ingija",
        "Izvor",
        "Jagodina",
        "Kacarevo",
        "Kanjiza",
        "Kovin",
        "Kragujevac",
        "Kraljevo",
        "Leskovac",
        "Loznica",
        "Melenci",
        "Nikinci",
        "Nova Pazova",
        "Novi Banovci",
        "Novi Becej",
        "Novi Belgrade",
        "Novi Pazar",
        "Novi Sad",
        "Odzaci",
        "Palic",
        "Paracin",
        "Petrovac",
        "Petrovaradin",
        "Pirot",
        "Popovac",
        "Priboj",
        "Prokuplje",
        "Ratkovo",
        "Ruma",
        "Rumenka",
        "Savski Venac",
        "Selo Mladenovac",
        "Senta",
        "Sibac",
        "Simanovci",
        "Sirig",
        "Smederevo",
        "Sombor",
        "Srbobran",
        "Sremcica",
        "Sremska Kamenica",
        "Sremska Mitrovica",
        "Sremski Karlovci",
        "Stara Pazova",
        "Stari Banovci",
        "Subotica",
        "Surcin",
        "Svilajnac",
        "Svrljig",
        "Temerin",
        "Titel",
        "Tornjos",
        "Ugrinovci",
        "Umcari",
        "Umka",
        "Vajska",
        "Valjevo",
        "Veternik",
        "Vrbas",
        "Zajecar",
        "Zemun Polje",
        "Zlatibor",
        "Zrenjanin",
        "Aranđelovac",
        "Badovinci",
        "Bajina Bašta",
        "Banovo Polje",
        "Barič",
        "Bečmen",
        "Belotić",
        "Biljača",
        "Bogatić",
        "Bogosavac",
        "Boljevci",
        "Brdarica",
        "Bukor",
        "Čačak",
        "Čajetina",
        "Ćićevac",
        "Čokešina",
        "Crna Bara",
        "Ćuprija",
        "Dobanovci",
        "Dobrić",
        "Donji Dobrić",
        "Donji Milanovac",
        "Draginje",
        "Dublje",
        "Duboka",
        "Ðurići",
        "Glušci",
        "Golubac",
        "Gornja Bukovica",
        "Grabovac",
        "Jablanica",
        "Jadranska Lešnica",
        "Jarebice",
        "Jelenča",
        "Jevremovac",
        "Joševa",
        "Kamenica",
        "Klenje",
        "Knjazevac",
        "Kolubara",
        "Kozjak",
        "Krivaja",
        "Krupanj",
        "Kruševac",
        "Lagja e Poshtme",
        "Lapovo",
        "Lazarevac",
        "Lešnica",
        "Lipnički Šor",
        "Lipolist",
        "Ljig",
        "Ljubovija",
        "Lugavčina",
        "Mačva",
        "Majdanpek",
        "Majur",
        "Mala Moštanica",
        "Mali Zvornik",
        "Metković",
        "Miratovac",
        "Morava",
        "Negotin",
        "Niš",
        "Nišava",
        "Novo Selo",
        "Obrenovac",
        "Osečina",
        "Osječenik",
        "Ostružnica",
        "Ovča",
        "Paraćin",
        "Pčinja",
        "Petkovica",
        "Pocerski Pričinović",
        "Podunavlje District",
        "Pomoravlje",
        "Požarevac",
        "Prijepolje",
        "Prislonica",
        "Prnjavor",
        "Radenka",
        "Radovnica",
        "Rajince",
        "Rasina",
        "Raška",
        "Ribari",
        "Rumska",
        "Rušanj",
        "Šabac",
        "Salaš Crnobarski",
        "Samoljica",
        "Ševarice",
        "Ševica",
        "Sinošević",
        "Sjenica",
        "Smederevska Palanka",
        "Sokolovica",
        "Sokolovo Brdo",
        "Sremčica",
        "Stepojevac",
        "Štitar",
        "Stubline",
        "Šumadija",
        "Sumulicë",
        "Surčin",
        "Tabanović",
        "Toplica",
        "Tršić",
        "Trstenik",
        "Turija",
        "Tutin",
        "Užice",
        "Uzveće",
        "Varna",
        "Velika Moštanica",
        "Vladimirci",
        "Vranić",
        "Vranje",
        "Vrnjačka Banja",
        "Zaječar",
        "Zemun",
        "Zminjak",
        "Žujince",
        "Zvečka",
        "Adorjan",
        "Aleksandrovo",
        "Alibunar",
        "Aradac",
        "Bačka Palanka",
        "Bačka Topola",
        "Bački Breg",
        "Bački Petrovac",
        "Bačko Gradište",
        "Bačko Petrovo Selo",
        "Banatska Topola",
        "Banatski Despotovac",
        "Banatski Dvor",
        "Banatski Karlovac",
        "Banatsko Karađorđevo",
        "Banatsko Veliko Selo",
        "Baranda",
        "Barice",
        "Bašaid",
        "Bečej",
        "Bela Crkva",
        "Belegiš",
        "Belo Blato",
        "Beška",
        "Bočar",
        "Bogojevo",
        "Boka",
        "Bosut",
        "Botoš",
        "Buđanovci",
        "Čelarevo",
        "Čenta",
        "Čestereg",
        "Čoka",
        "Čortanovci",
        "Crepaja",
        "Čurug",
        "Debeljača",
        "Despotovo",
        "Dobrica",
        "Doroslovo",
        "Ðurđevo",
        "Ečka",
        "Elemir",
        "Farkaždin",
        "Gakovo",
        "Gardinovci",
        "Gložan",
        "Gornji Breg",
        "Grabovci",
        "Gudurica",
        "Hajdučica",
        "Hetin",
        "Hrtkovci",
        "Idvor",
        "Ilandža",
        "Inđija",
        "Irig",
        "Izbište",
        "Janošik",
        "Jarak",
        "Jarkovac",
        "Jaša Tomić",
        "Jazovo",
        "Jermenovci",
        "Kanjiža",
        "Kikinda",
        "Kisač",
        "Klek",
        "Klenak",
        "Knićanin",
        "Kolut",
        "Konak",
        "Kovačica",
        "Kovilj",
        "Krajišnik",
        "Krčedin",
        "Kulpin",
        "Kumane",
        "Kupinovo",
        "Kupusina",
        "Kuštilj",
        "Lazarevo",
        "Ljukovo",
        "Lok",
        "Lokve",
        "Lukićevo",
        "Mačvanska Mitrovica",
        "Maglić",
        "Margita",
        "Međa",
        "Mihajlovo",
        "Mokrin",
        "Mol",
        "Mošorin",
        "Nakovo",
        "Neuzina",
        "Nikolinci",
        "Nova Crnja",
        "Novi Itebej",
        "Novi Karlovci",
        "Novi Kneževac",
        "Novi Kozarci",
        "Novi Slankamen",
        "Novo Miloševo",
        "Obrovac",
        "Opovo",
        "Orlovat",
        "Ostojićevo",
        "Padej",
        "Padina",
        "Pančevo",
        "Pavliš",
        "Pećinci",
        "Perlez",
        "Plandište",
        "Platičevo",
        "Prigrevica",
        "Putinci",
        "Radenković",
        "Radojevo",
        "Ravni Topolovac",
        "Ravnje",
        "Ravno Selo",
        "Riđica",
        "Rusko Selo",
        "Sajan",
        "Šajkaš",
        "Sakule",
        "Salaš Noćajski",
        "Samoš",
        "Sanad",
        "Šašinci",
        "Sečanj",
        "Sefkerin",
        "Seleuš",
        "Šimanovci",
        "Sonta",
        "Srpska Crnja",
        "Srpski Itebej",
        "Stajićevo",
        "Stanišić",
        "Stari Lec",
        "Stepanovićevo",
        "Surduk",
        "Sutjeska",
        "Taraš",
        "Tiszahegyes",
        "Toba",
        "Tomaševac",
        "Torak",
        "Torda",
        "Uljma",
        "Uzdin",
        "Velika Greda",
        "Veliki Gaj",
        "Veliko Središte",
        "Vilovo",
        "Višnjićevo",
        "Vladimirovac",
        "Vlajkovac",
        "Vojka",
        "Vojvoda Stepa",
        "Vrdnik",
        "Vršac",
        "Žabalj",
        "Žitište",
        "Zmajevo"
    ];
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return auth()->check();
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {

        return [
            'email' => ['string', 'email', 'max:255','nullable',
                Rule::unique('users')->ignore(auth()->id())
            ],
            'password' => [Rules\Password::defaults(), 'string', 'nullable'],
            'phone' => ['string', 'max:12', 'unique:addresses','nullable'],
            'location' =>   ['string', Rule::in($this->cities),'nullable'],
        ];
    }
}
